# Generated by Django 5.1.7 on 2025-08-09 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('intelligence', models.IntegerField(default=0)),
                ('agility', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('magic', models.IntegerField(default=0)),
                ('social', models.IntegerField(default=0)),
                ('default_image', models.ImageField(upload_to='character_classes/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intelligence', models.IntegerField(default=0, help_text='Intelligence score')),
                ('agility', models.IntegerField(default=0, help_text='Agility score')),
                ('strength', models.IntegerField(default=0, help_text='Strength score')),
                ('magic', models.IntegerField(default=0, help_text='Magic score')),
                ('social', models.IntegerField(default=0, help_text='Social score')),
                ('image', models.ImageField(blank=True, null=True, upload_to='player_images/')),
                ('character_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.characterclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
