# Generated by Django 5.1.7 on 2025-08-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_characterclass_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterclass',
            old_name='social',
            new_name='charism',
        ),
        migrations.RemoveField(
            model_name='player',
            name='social',
        ),
        migrations.AddField(
            model_name='characterclass',
            name='constitution',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='wisdom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='charism',
            field=models.IntegerField(default=0, help_text='charism score'),
        ),
        migrations.AddField(
            model_name='player',
            name='constitution',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wisdom',
            field=models.IntegerField(default=0),
        ),
    ]
