# Generated by Django 5.1.7 on 2025-08-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_social_characterclass_charism_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='default_image',
        ),
        migrations.AddField(
            model_name='characterclass',
            name='default_image_female',
            field=models.ImageField(blank=True, null=True, upload_to='character_classes/male/'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='default_image_male',
            field=models.ImageField(blank=True, null=True, upload_to='character_classes/male/'),
        ),
        migrations.AddField(
            model_name='player',
            name='default_image_choice',
            field=models.CharField(choices=[('M', 'MaleIm'), ('F', 'FemaleIm')], default='M', max_length=1),
        ),
    ]
