# Generated by Django 5.1.7 on 2025-05-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_book_edition_book_finished_date_book_global_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='finished_date',
        ),
        migrations.AddField(
            model_name='book',
            name='finished_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='finished_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='finished_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
