# Generated by Django 5.1.7 on 2025-05-15 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_remove_book_finished_date_book_finished_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='global_rate',
            field=models.IntegerField(blank=True, default=0, help_text='Note entre 0 et 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='global_rate',
            field=models.IntegerField(blank=True, default=0, help_text='Note entre 0 et 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='series',
            name='global_rate',
            field=models.IntegerField(blank=True, default=0, help_text='Note entre 0 et 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
