# Generated by Django 5.1.7 on 2025-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_book_global_rate_alter_movie_global_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='finished_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='finished_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='finished_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='finished_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='finished_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='finished_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
