# Generated by Django 5.1.7 on 2025-05-22 11:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_movie_finished_day_movie_finished_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_cloud',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
