# Generated by Django 5.1.7 on 2025-05-22 12:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_book_image_cloud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_cloud',
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
