# Generated by Django 5.1.7 on 2025-05-22 15:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_alter_book_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('finished_year', models.PositiveIntegerField(blank=True, null=True)),
                ('finished_month', models.PositiveIntegerField(blank=True, null=True)),
                ('finished_day', models.PositiveIntegerField(blank=True, null=True)),
                ('global_rate', models.IntegerField(blank=True, default=0, help_text='Note entre 0 et 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='manga_images/')),
                ('genres', models.ManyToManyField(blank=True, to='media.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
