# Generated by Django 5.1.7 on 2025-06-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_alter_book_author_alter_movie_director_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='statut',
            field=models.CharField(blank=True, choices=[('Fini', 'Read'), ('Arrété', 'stoped'), ('En attente', 'later')], max_length=10, null=True),
        ),
    ]
