# Generated by Django 5.1.7 on 2025-06-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_manga_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='statut',
            field=models.CharField(blank=True, choices=[('Fini', 'Fini'), ('Arrêté', 'Arrêté'), ('En attente', 'En attente')], max_length=10, null=True),
        ),
    ]
