# Generated by Django 5.1.7 on 2025-06-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_alter_manga_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='read',
        ),
        migrations.AddField(
            model_name='book',
            name='statut',
            field=models.CharField(blank=True, choices=[('Fini', 'Fini'), ('Arrêté', 'Arrêté'), ('En attente', 'En attente')], max_length=10, null=True),
        ),
    ]
