# Generated by Django 5.1.7 on 2025-06-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_manga_stop_area_alter_manga_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='stop_area',
            new_name='episode',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='stop_area',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='watched',
        ),
        migrations.RemoveField(
            model_name='series',
            name='completed',
        ),
        migrations.AddField(
            model_name='manga',
            name='scan',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='statut',
            field=models.CharField(blank=True, choices=[('Fini', 'Fini'), ('Arrêté', 'Arrêté'), ('En attente', 'En attente')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='saison',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='statut',
            field=models.CharField(blank=True, choices=[('Fini', 'Fini'), ('Arrêté', 'Arrêté'), ('En cours', 'En cours'), ('En attente', 'En attente')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='statut',
            field=models.CharField(blank=True, choices=[('Fini', 'Fini'), ('Arrêté', 'Arrêté'), ('En cours', 'En cours'), ('En attente', 'En attente')], max_length=10, null=True),
        ),
    ]
