# Generated by Django 5.1.7 on 2025-06-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_rename_stop_area_series_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='reading_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
