# Generated by Django 5.1.7 on 2025-06-09 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_manga_reading_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='nb_pages',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
