# Generated by Django 5.1.7 on 2025-06-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_book_nb_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='nb_pages',
            new_name='pageCount',
        ),
    ]
