# Generated by Django 5.1.7 on 2025-07-31 13:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0020_userbackup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('pageCount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(blank=True, choices=[('Fini', 'Fini'), ('Arrêté', 'Arrêté'), ('En cours', 'En cours'), ('En attente', 'En attente')], max_length=10, null=True)),
                ('finished_year', models.PositiveIntegerField(blank=True, null=True)),
                ('finished_month', models.PositiveIntegerField(blank=True, null=True)),
                ('finished_day', models.PositiveIntegerField(blank=True, null=True)),
                ('global_rate', models.IntegerField(blank=True, default=0, help_text='Note entre 0 et 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('genres', models.ManyToManyField(blank=True, to='media.genre')),
                ('public_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.publicbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('media.userbook',),
        ),
    ]
