# Generated by Django 5.1.7 on 2025-08-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0022_delete_book_book_delete_userbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='public_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='media.publicbook'),
        ),
    ]
