# Generated by Django 5.1.7 on 2025-08-04 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0023_alter_book_public_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='manga_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='manga',
            name='image',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='title',
        ),
        migrations.AddField(
            model_name='manga',
            name='public_manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='media.publicmanga'),
        ),
    ]
