# Generated by Django 5.1.7 on 2025-08-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0024_publicmanga_remove_manga_image_remove_manga_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='statut',
            field=models.CharField(blank=True, choices=[('Fini', 'Fini'), ('Arrêté', 'Arrêté'), ('En cours', 'En cours'), ('En attente', 'En attente'), ('My List', 'My List')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='statut',
            field=models.CharField(blank=True, choices=[('Fini', 'Fini'), ('Arrêté', 'Arrêté'), ('En cours', 'En cours'), ('En attente', 'En attente'), ('My List', 'My List')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='statut',
            field=models.CharField(blank=True, choices=[('Fini', 'Fini'), ('Arrêté', 'Arrêté'), ('En attente', 'En attente'), ('My List', 'My List')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='statut',
            field=models.CharField(blank=True, choices=[('Fini', 'Fini'), ('Arrêté', 'Arrêté'), ('En cours', 'En cours'), ('En attente', 'En attente'), ('My List', 'My List')], max_length=10, null=True),
        ),
    ]
